name: 'Provision Azure Runner'
description: 'Provisions an Azure VM as a GitHub Actions self-hosted runner'

inputs:
  azure-credentials:
    description: 'Azure service principal credentials (JSON)'
    required: true
  github-token:
    description: 'GitHub token for runner registration'
    required: true
  ubuntu-version:
    description: 'Ubuntu version (e.g., 24.04)'
    required: true
  ubuntu-lts:
    description: 'Ubuntu LTS version for Azure (e.g., 24.04-LTS)'
    required: true
  image-offer:
    description: 'Azure image offer (e.g., ubuntu-24_04-lts)'
    required: true
  image-sku:
    description: 'Azure image SKU (e.g., server)'
    required: true
  pr-number:
    description: 'PR number for tagging resources'
    required: false
    default: ''
  use-regular-vm:
    description: 'Use regular VM (default: true)'
    required: false
    default: 'true'

outputs:
  vm-name:
    description: 'Name of the provisioned VM'
    value: ${{ steps.provision.outputs.vm_name }}

runs:
  using: 'composite'
  steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ inputs.azure-credentials }}

    - name: Provision Azure VM
      id: provision
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GITHUB_RUN_ID: ${{ github.run_id }}
      run: |
        set -euo pipefail  # Exit on any error, preserve pipe exit codes

        chmod +x scripts/azure/provision-runner.sh

        ARGS="--ubuntu-version ${{ inputs.ubuntu-lts }} \
          --image-offer ${{ inputs.image-offer }} \
          --image-sku ${{ inputs.image-sku }} \
          --no-cleanup"

        if [ "${{ inputs.use-regular-vm }}" = "true" ]; then
          ARGS="$ARGS --regular-vm"
        fi

        if [ -n "${{ inputs.pr-number }}" ]; then
          ARGS="$ARGS --pr-number ${{ inputs.pr-number }}"
        fi

        # Run provision script - with pipefail, tee will preserve exit code
        ./scripts/azure/provision-runner.sh $ARGS 2>&1 | tee provision-log-${{ inputs.ubuntu-version }}.txt

        # Extract VM name from logs (only reached if provision succeeded)
        VM_NAME=$(grep "^  Name:" provision-log-${{ inputs.ubuntu-version }}.txt | awk '{print $NF}' || echo "none")
        echo "vm_name=$VM_NAME" >> $GITHUB_OUTPUT
        echo "::notice title=Azure VM Provisioned::$VM_NAME for Ubuntu ${{ inputs.ubuntu-version }}"
